### ISSUE TITLE
lessvars doesnt work

### ISSUE THREAD

**Issue by millievn** [mit123suki/next-ant-less#2]
I change values in lessvars.less and it doesnt work.

**Comment by EviLgorilla** [comment]
@qiwang97 
> I change values in lessvars.less and it doesnt work.

`@import "~antd/dist/antd.less";`

**Comment by mit123suki** [comment]
Hi, Sorry for the delayed response. I have been bit busy with other works so couldn't respond. 

Anyway, use https://github.com/mit123suki/next-ant-setup

This repo shows how to setup with ant without customizing the webpack. But this requires some effort for first time as detailed in readme if you creating project from scratch.
